// Calorie database based on USDA food database values
// Values are per 100g unless otherwise specified

export interface CalorieEntry {
  name: string;
  caloriesPer100g: number;
  defaultUnit: string;
  defaultAmount: number;
  gramsPerUnit: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export const CALORIE_DATABASE: Record<string, CalorieEntry> = {
  // Proteins
  'chicken breast': {
    name: 'Chicken Breast',
    caloriesPer100g: 165,
    defaultUnit: 'oz',
    defaultAmount: 4,
    gramsPerUnit: 28.35,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
  },
  'chicken thigh': {
    name: 'Chicken Thigh',
    caloriesPer100g: 209,
    defaultUnit: 'oz',
    defaultAmount: 4,
    gramsPerUnit: 28.35,
    protein: 26,
    carbs: 0,
    fat: 10.9,
    fiber: 0,
  },
  'ground beef': {
    name: 'Ground Beef (80/20)',
    caloriesPer100g: 254,
    defaultUnit: 'oz',
    defaultAmount: 4,
    gramsPerUnit: 28.35,
    protein: 17.2,
    carbs: 0,
    fat: 20,
    fiber: 0,
  },
  'ground beef lean': {
    name: 'Ground Beef (90/10)',
    caloriesPer100g: 176,
    defaultUnit: 'oz',
    defaultAmount: 4,
    gramsPerUnit: 28.35,
    protein: 20,
    carbs: 0,
    fat: 10,
    fiber: 0,
  },
  'salmon': {
    name: 'Salmon',
    caloriesPer100g: 208,
    defaultUnit: 'oz',
    defaultAmount: 4,
    gramsPerUnit: 28.35,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  'shrimp': {
    name: 'Shrimp',
    caloriesPer100g: 99,
    defaultUnit: 'oz',
    defaultAmount: 4,
    gramsPerUnit: 28.35,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
  },
  'eggs': {
    name: 'Eggs',
    caloriesPer100g: 155,
    defaultUnit: 'large',
    defaultAmount: 1,
    gramsPerUnit: 50,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
  },
  'bacon': {
    name: 'Bacon',
    caloriesPer100g: 541,
    defaultUnit: 'slice',
    defaultAmount: 2,
    gramsPerUnit: 8,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    fiber: 0,
  },
  'tofu': {
    name: 'Tofu (firm)',
    caloriesPer100g: 144,
    defaultUnit: 'oz',
    defaultAmount: 4,
    gramsPerUnit: 28.35,
    protein: 17,
    carbs: 3,
    fat: 9,
    fiber: 2,
  },

  // Dairy
  'milk': {
    name: 'Milk (whole)',
    caloriesPer100g: 61,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 244,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
  },
  'milk skim': {
    name: 'Milk (skim)',
    caloriesPer100g: 34,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 244,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
  },
  'cheese cheddar': {
    name: 'Cheddar Cheese',
    caloriesPer100g: 403,
    defaultUnit: 'oz',
    defaultAmount: 1,
    gramsPerUnit: 28.35,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
  },
  'cheese mozzarella': {
    name: 'Mozzarella Cheese',
    caloriesPer100g: 280,
    defaultUnit: 'oz',
    defaultAmount: 1,
    gramsPerUnit: 28.35,
    protein: 22,
    carbs: 2.2,
    fat: 22,
    fiber: 0,
  },
  'butter': {
    name: 'Butter',
    caloriesPer100g: 717,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 14,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    fiber: 0,
  },
  'cream cheese': {
    name: 'Cream Cheese',
    caloriesPer100g: 342,
    defaultUnit: 'oz',
    defaultAmount: 1,
    gramsPerUnit: 28.35,
    protein: 6,
    carbs: 4,
    fat: 34,
    fiber: 0,
  },
  'yogurt greek': {
    name: 'Greek Yogurt',
    caloriesPer100g: 97,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 245,
    protein: 9,
    carbs: 3.6,
    fat: 5,
    fiber: 0,
  },
  'sour cream': {
    name: 'Sour Cream',
    caloriesPer100g: 198,
    defaultUnit: 'tbsp',
    defaultAmount: 2,
    gramsPerUnit: 12,
    protein: 2.4,
    carbs: 4.6,
    fat: 19.4,
    fiber: 0,
  },

  // Grains & Carbs
  'rice white': {
    name: 'White Rice (cooked)',
    caloriesPer100g: 130,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 158,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
  },
  'rice brown': {
    name: 'Brown Rice (cooked)',
    caloriesPer100g: 112,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 195,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
  },
  'pasta': {
    name: 'Pasta (cooked)',
    caloriesPer100g: 131,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 140,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
  },
  'bread white': {
    name: 'White Bread',
    caloriesPer100g: 265,
    defaultUnit: 'slice',
    defaultAmount: 1,
    gramsPerUnit: 25,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    fiber: 2.7,
  },
  'bread whole wheat': {
    name: 'Whole Wheat Bread',
    caloriesPer100g: 247,
    defaultUnit: 'slice',
    defaultAmount: 1,
    gramsPerUnit: 28,
    protein: 13,
    carbs: 41,
    fat: 4.2,
    fiber: 7,
  },
  'flour all purpose': {
    name: 'All-Purpose Flour',
    caloriesPer100g: 364,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 125,
    protein: 10,
    carbs: 76,
    fat: 1,
    fiber: 2.7,
  },
  'oats': {
    name: 'Oats',
    caloriesPer100g: 389,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 81,
    protein: 17,
    carbs: 66,
    fat: 7,
    fiber: 11,
  },
  'quinoa': {
    name: 'Quinoa (cooked)',
    caloriesPer100g: 120,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 185,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
    fiber: 2.8,
  },
  'potato': {
    name: 'Potato',
    caloriesPer100g: 77,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 150,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.2,
  },
  'sweet potato': {
    name: 'Sweet Potato',
    caloriesPer100g: 86,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 130,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
  },

  // Vegetables
  'broccoli': {
    name: 'Broccoli',
    caloriesPer100g: 34,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 91,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
  },
  'spinach': {
    name: 'Spinach',
    caloriesPer100g: 23,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 30,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
  },
  'carrot': {
    name: 'Carrot',
    caloriesPer100g: 41,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 61,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
  },
  'onion': {
    name: 'Onion',
    caloriesPer100g: 40,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 110,
    protein: 1.1,
    carbs: 9,
    fat: 0.1,
    fiber: 1.7,
  },
  'garlic': {
    name: 'Garlic',
    caloriesPer100g: 149,
    defaultUnit: 'clove',
    defaultAmount: 2,
    gramsPerUnit: 3,
    protein: 6.4,
    carbs: 33,
    fat: 0.5,
    fiber: 2.1,
  },
  'tomato': {
    name: 'Tomato',
    caloriesPer100g: 18,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 123,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
  },
  'bell pepper': {
    name: 'Bell Pepper',
    caloriesPer100g: 31,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 119,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
  },
  'mushroom': {
    name: 'Mushrooms',
    caloriesPer100g: 22,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 70,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1,
  },
  'zucchini': {
    name: 'Zucchini',
    caloriesPer100g: 17,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 196,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
  },
  'lettuce': {
    name: 'Lettuce',
    caloriesPer100g: 15,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 36,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
  },
  'cucumber': {
    name: 'Cucumber',
    caloriesPer100g: 15,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 201,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
  },
  'celery': {
    name: 'Celery',
    caloriesPer100g: 16,
    defaultUnit: 'stalk',
    defaultAmount: 2,
    gramsPerUnit: 40,
    protein: 0.7,
    carbs: 3,
    fat: 0.2,
    fiber: 1.6,
  },
  'corn': {
    name: 'Corn',
    caloriesPer100g: 86,
    defaultUnit: 'ear',
    defaultAmount: 1,
    gramsPerUnit: 90,
    protein: 3.2,
    carbs: 19,
    fat: 1.2,
    fiber: 2.7,
  },
  'green beans': {
    name: 'Green Beans',
    caloriesPer100g: 31,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 100,
    protein: 1.8,
    carbs: 7,
    fat: 0.1,
    fiber: 3.4,
  },
  'asparagus': {
    name: 'Asparagus',
    caloriesPer100g: 20,
    defaultUnit: 'spear',
    defaultAmount: 5,
    gramsPerUnit: 16,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
    fiber: 2.1,
  },
  'cabbage': {
    name: 'Cabbage',
    caloriesPer100g: 25,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 89,
    protein: 1.3,
    carbs: 6,
    fat: 0.1,
    fiber: 2.5,
  },
  'cauliflower': {
    name: 'Cauliflower',
    caloriesPer100g: 25,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 100,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2,
  },
  'kale': {
    name: 'Kale',
    caloriesPer100g: 49,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 67,
    protein: 4.3,
    carbs: 9,
    fat: 0.9,
    fiber: 3.6,
  },
  'avocado': {
    name: 'Avocado',
    caloriesPer100g: 160,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 150,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
  },

  // Fruits
  'apple': {
    name: 'Apple',
    caloriesPer100g: 52,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 182,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
  },
  'banana': {
    name: 'Banana',
    caloriesPer100g: 89,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 118,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
  },
  'orange': {
    name: 'Orange',
    caloriesPer100g: 47,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 131,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
  },
  'strawberry': {
    name: 'Strawberries',
    caloriesPer100g: 32,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 144,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
  },
  'blueberry': {
    name: 'Blueberries',
    caloriesPer100g: 57,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 148,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    fiber: 2.4,
  },
  'lemon': {
    name: 'Lemon',
    caloriesPer100g: 29,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 58,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.3,
    fiber: 2.8,
  },
  'lime': {
    name: 'Lime',
    caloriesPer100g: 30,
    defaultUnit: 'medium',
    defaultAmount: 1,
    gramsPerUnit: 67,
    protein: 0.7,
    carbs: 11,
    fat: 0.2,
    fiber: 2.8,
  },
  'grapes': {
    name: 'Grapes',
    caloriesPer100g: 69,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 151,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    fiber: 0.9,
  },
  'mango': {
    name: 'Mango',
    caloriesPer100g: 60,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 165,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
  },
  'pineapple': {
    name: 'Pineapple',
    caloriesPer100g: 50,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 165,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    fiber: 1.4,
  },

  // Oils & Fats
  'olive oil': {
    name: 'Olive Oil',
    caloriesPer100g: 884,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 14,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
  },
  'vegetable oil': {
    name: 'Vegetable Oil',
    caloriesPer100g: 884,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 14,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
  },
  'coconut oil': {
    name: 'Coconut Oil',
    caloriesPer100g: 862,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 14,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
  },

  // Legumes & Beans
  'black beans': {
    name: 'Black Beans (cooked)',
    caloriesPer100g: 132,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 172,
    protein: 8.9,
    carbs: 24,
    fat: 0.5,
    fiber: 8.7,
  },
  'chickpeas': {
    name: 'Chickpeas (cooked)',
    caloriesPer100g: 164,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    fiber: 7.6,
  },
  'lentils': {
    name: 'Lentils (cooked)',
    caloriesPer100g: 116,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 198,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
  },
  'kidney beans': {
    name: 'Kidney Beans (cooked)',
    caloriesPer100g: 127,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 177,
    protein: 8.7,
    carbs: 22,
    fat: 0.5,
    fiber: 6.4,
  },

  // Nuts & Seeds
  'almonds': {
    name: 'Almonds',
    caloriesPer100g: 579,
    defaultUnit: 'oz',
    defaultAmount: 1,
    gramsPerUnit: 28.35,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
  },
  'walnuts': {
    name: 'Walnuts',
    caloriesPer100g: 654,
    defaultUnit: 'oz',
    defaultAmount: 1,
    gramsPerUnit: 28.35,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 6.7,
  },
  'peanuts': {
    name: 'Peanuts',
    caloriesPer100g: 567,
    defaultUnit: 'oz',
    defaultAmount: 1,
    gramsPerUnit: 28.35,
    protein: 26,
    carbs: 16,
    fat: 49,
    fiber: 8.5,
  },
  'peanut butter': {
    name: 'Peanut Butter',
    caloriesPer100g: 588,
    defaultUnit: 'tbsp',
    defaultAmount: 2,
    gramsPerUnit: 16,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
  },

  // Sweeteners
  'sugar': {
    name: 'Sugar',
    caloriesPer100g: 387,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 12.5,
    protein: 0,
    carbs: 100,
    fat: 0,
    fiber: 0,
  },
  'honey': {
    name: 'Honey',
    caloriesPer100g: 304,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 21,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    fiber: 0.2,
  },
  'maple syrup': {
    name: 'Maple Syrup',
    caloriesPer100g: 260,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 20,
    protein: 0,
    carbs: 67,
    fat: 0.1,
    fiber: 0,
  },

  // Condiments & Sauces
  'soy sauce': {
    name: 'Soy Sauce',
    caloriesPer100g: 53,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 16,
    protein: 8.1,
    carbs: 4.9,
    fat: 0.6,
    fiber: 0.8,
  },
  'ketchup': {
    name: 'Ketchup',
    caloriesPer100g: 112,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 17,
    protein: 1.7,
    carbs: 26,
    fat: 0.4,
    fiber: 0.3,
  },
  'mayonnaise': {
    name: 'Mayonnaise',
    caloriesPer100g: 680,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 14,
    protein: 1,
    carbs: 0.6,
    fat: 75,
    fiber: 0,
  },
  'mustard': {
    name: 'Mustard',
    caloriesPer100g: 66,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 5,
    protein: 4.4,
    carbs: 5.3,
    fat: 4,
    fiber: 3.3,
  },
  'salsa': {
    name: 'Salsa',
    caloriesPer100g: 36,
    defaultUnit: 'tbsp',
    defaultAmount: 2,
    gramsPerUnit: 16,
    protein: 0.9,
    carbs: 7.2,
    fat: 0.2,
    fiber: 1.4,
  },
  'tomato sauce': {
    name: 'Tomato Sauce',
    caloriesPer100g: 29,
    defaultUnit: 'cup',
    defaultAmount: 0.5,
    gramsPerUnit: 245,
    protein: 1.3,
    carbs: 7,
    fat: 0.2,
    fiber: 1.5,
  },

  // Spices (minimal calories but included for completeness)
  'salt': {
    name: 'Salt',
    caloriesPer100g: 0,
    defaultUnit: 'tsp',
    defaultAmount: 1,
    gramsPerUnit: 6,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  'black pepper': {
    name: 'Black Pepper',
    caloriesPer100g: 251,
    defaultUnit: 'tsp',
    defaultAmount: 0.5,
    gramsPerUnit: 2.3,
    protein: 10,
    carbs: 64,
    fat: 3.3,
    fiber: 25,
  },
  'paprika': {
    name: 'Paprika',
    caloriesPer100g: 282,
    defaultUnit: 'tsp',
    defaultAmount: 1,
    gramsPerUnit: 2.3,
    protein: 14,
    carbs: 54,
    fat: 13,
    fiber: 35,
  },
  'cumin': {
    name: 'Cumin',
    caloriesPer100g: 375,
    defaultUnit: 'tsp',
    defaultAmount: 1,
    gramsPerUnit: 2.1,
    protein: 18,
    carbs: 44,
    fat: 22,
    fiber: 11,
  },
  'oregano': {
    name: 'Oregano (dried)',
    caloriesPer100g: 265,
    defaultUnit: 'tsp',
    defaultAmount: 1,
    gramsPerUnit: 1,
    protein: 9,
    carbs: 69,
    fat: 4.3,
    fiber: 43,
  },
  'basil': {
    name: 'Basil (fresh)',
    caloriesPer100g: 22,
    defaultUnit: 'tbsp',
    defaultAmount: 2,
    gramsPerUnit: 5,
    protein: 3.2,
    carbs: 2.7,
    fat: 0.6,
    fiber: 1.6,
  },
  'cilantro': {
    name: 'Cilantro',
    caloriesPer100g: 23,
    defaultUnit: 'tbsp',
    defaultAmount: 2,
    gramsPerUnit: 4,
    protein: 2.1,
    carbs: 3.7,
    fat: 0.5,
    fiber: 2.8,
  },
  'parsley': {
    name: 'Parsley',
    caloriesPer100g: 36,
    defaultUnit: 'tbsp',
    defaultAmount: 2,
    gramsPerUnit: 4,
    protein: 3,
    carbs: 6.3,
    fat: 0.8,
    fiber: 3.3,
  },
  'ginger': {
    name: 'Ginger',
    caloriesPer100g: 80,
    defaultUnit: 'tbsp',
    defaultAmount: 1,
    gramsPerUnit: 6,
    protein: 1.8,
    carbs: 18,
    fat: 0.8,
    fiber: 2,
  },
  'cinnamon': {
    name: 'Cinnamon',
    caloriesPer100g: 247,
    defaultUnit: 'tsp',
    defaultAmount: 1,
    gramsPerUnit: 2.6,
    protein: 4,
    carbs: 81,
    fat: 1.2,
    fiber: 53,
  },

  // Beverages / Liquids
  'chicken broth': {
    name: 'Chicken Broth',
    caloriesPer100g: 4,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 240,
    protein: 0.5,
    carbs: 0.4,
    fat: 0,
    fiber: 0,
  },
  'vegetable broth': {
    name: 'Vegetable Broth',
    caloriesPer100g: 3,
    defaultUnit: 'cup',
    defaultAmount: 1,
    gramsPerUnit: 240,
    protein: 0.1,
    carbs: 0.5,
    fat: 0,
    fiber: 0,
  },
  'wine white': {
    name: 'White Wine',
    caloriesPer100g: 82,
    defaultUnit: 'cup',
    defaultAmount: 0.5,
    gramsPerUnit: 147,
    protein: 0.1,
    carbs: 2.6,
    fat: 0,
    fiber: 0,
  },
  'wine red': {
    name: 'Red Wine',
    caloriesPer100g: 85,
    defaultUnit: 'cup',
    defaultAmount: 0.5,
    gramsPerUnit: 147,
    protein: 0.1,
    carbs: 2.6,
    fat: 0,
    fiber: 0,
  },
};

// Unit conversion helpers
export const UNIT_CONVERSIONS: Record<string, number> = {
  // Volume (to ml)
  'tsp': 4.929,
  'tbsp': 14.787,
  'cup': 236.588,
  'fl oz': 29.574,
  'ml': 1,
  'l': 1000,
  // Weight (to grams)
  'oz': 28.35,
  'lb': 453.592,
  'g': 1,
  'kg': 1000,
};

// Common unit aliases
export const UNIT_ALIASES: Record<string, string> = {
  'teaspoon': 'tsp',
  'teaspoons': 'tsp',
  'tablespoon': 'tbsp',
  'tablespoons': 'tbsp',
  'cups': 'cup',
  'ounce': 'oz',
  'ounces': 'oz',
  'pound': 'lb',
  'pounds': 'lb',
  'gram': 'g',
  'grams': 'g',
  'kilogram': 'kg',
  'kilograms': 'kg',
  'milliliter': 'ml',
  'milliliters': 'ml',
  'liter': 'l',
  'liters': 'l',
  'piece': 'piece',
  'pieces': 'piece',
  'slice': 'slice',
  'slices': 'slice',
  'clove': 'clove',
  'cloves': 'clove',
  'stalk': 'stalk',
  'stalks': 'stalk',
  'sprig': 'sprig',
  'sprigs': 'sprig',
  'large': 'large',
  'medium': 'medium',
  'small': 'small',
  'whole': 'whole',
  'ear': 'ear',
  'spear': 'spear',
};
