import { Timestamp } from 'firebase/firestore';
import { Recipe, Ingredient, NutritionInfo } from '@/types';

// Helper to create timestamp-like objects for seeds
const createTimestamp = () => Timestamp.now();

// Sample ingredients with calorie data
const SEED_INGREDIENTS = {
  chickenBreast: (amount: number): Ingredient => ({
    name: 'chicken breast',
    amount,
    unit: 'oz',
    calories: Math.round(amount * 28.35 * 1.65),
    optional: false,
  }),
  oliveOil: (amount: number): Ingredient => ({
    name: 'olive oil',
    amount,
    unit: 'tbsp',
    calories: Math.round(amount * 120),
    optional: false,
  }),
  garlic: (amount: number): Ingredient => ({
    name: 'garlic',
    amount,
    unit: 'clove',
    calories: Math.round(amount * 4),
    optional: false,
  }),
  onion: (amount: number): Ingredient => ({
    name: 'onion',
    amount,
    unit: 'medium',
    calories: Math.round(amount * 44),
    optional: false,
  }),
  salt: (amount: number): Ingredient => ({
    name: 'salt',
    amount,
    unit: 'tsp',
    calories: 0,
    optional: false,
  }),
  pepper: (amount: number): Ingredient => ({
    name: 'black pepper',
    amount,
    unit: 'tsp',
    calories: Math.round(amount * 6),
    optional: false,
  }),
  pasta: (amount: number): Ingredient => ({
    name: 'pasta',
    amount,
    unit: 'oz',
    calories: Math.round(amount * 28.35 * 1.31),
    optional: false,
  }),
  tomatoSauce: (amount: number): Ingredient => ({
    name: 'tomato sauce',
    amount,
    unit: 'cup',
    calories: Math.round(amount * 70),
    optional: false,
  }),
  parmesan: (amount: number): Ingredient => ({
    name: 'parmesan cheese',
    amount,
    unit: 'oz',
    calories: Math.round(amount * 28.35 * 4.31),
    optional: false,
  }),
  basil: (amount: number): Ingredient => ({
    name: 'fresh basil',
    amount,
    unit: 'tbsp',
    calories: Math.round(amount * 1),
    optional: false,
  }),
  eggs: (amount: number): Ingredient => ({
    name: 'eggs',
    amount,
    unit: 'large',
    calories: Math.round(amount * 78),
    optional: false,
  }),
  butter: (amount: number): Ingredient => ({
    name: 'butter',
    amount,
    unit: 'tbsp',
    calories: Math.round(amount * 102),
    optional: false,
  }),
  flour: (amount: number): Ingredient => ({
    name: 'all-purpose flour',
    amount,
    unit: 'cup',
    calories: Math.round(amount * 455),
    optional: false,
  }),
  sugar: (amount: number): Ingredient => ({
    name: 'sugar',
    amount,
    unit: 'cup',
    calories: Math.round(amount * 774),
    optional: false,
  }),
  milk: (amount: number): Ingredient => ({
    name: 'milk',
    amount,
    unit: 'cup',
    calories: Math.round(amount * 149),
    optional: false,
  }),
  rice: (amount: number): Ingredient => ({
    name: 'white rice',
    amount,
    unit: 'cup',
    calories: Math.round(amount * 206),
    optional: false,
  }),
  soySauce: (amount: number): Ingredient => ({
    name: 'soy sauce',
    amount,
    unit: 'tbsp',
    calories: Math.round(amount * 9),
    optional: false,
  }),
  ginger: (amount: number): Ingredient => ({
    name: 'fresh ginger',
    amount,
    unit: 'tbsp',
    calories: Math.round(amount * 5),
    optional: false,
  }),
  bellPepper: (amount: number): Ingredient => ({
    name: 'bell pepper',
    amount,
    unit: 'medium',
    calories: Math.round(amount * 37),
    optional: false,
  }),
  broccoli: (amount: number): Ingredient => ({
    name: 'broccoli',
    amount,
    unit: 'cup',
    calories: Math.round(amount * 31),
    optional: false,
  }),
  lemon: (amount: number): Ingredient => ({
    name: 'lemon',
    amount,
    unit: 'medium',
    calories: Math.round(amount * 17),
    optional: false,
  }),
  honey: (amount: number): Ingredient => ({
    name: 'honey',
    amount,
    unit: 'tbsp',
    calories: Math.round(amount * 64),
    optional: false,
  }),
};

// Seed recipes
export const SEED_RECIPES: Omit<Recipe, 'id' | 'createdAt'>[] = [
  {
    title: 'Classic Lemon Herb Chicken',
    description: 'Juicy, flavorful chicken breast seasoned with fresh herbs and bright lemon. Perfect for a quick weeknight dinner that tastes gourmet.',
    imageURL: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
    authorId: 'chef_admin',
    authorName: 'Chef Maria',
    isOfficial: true,
    category: 'dinner',
    cuisine: 'mediterranean',
    difficulty: 'easy',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    ingredients: [
      SEED_INGREDIENTS.chickenBreast(24),
      SEED_INGREDIENTS.oliveOil(2),
      SEED_INGREDIENTS.garlic(4),
      SEED_INGREDIENTS.lemon(2),
      { name: 'fresh rosemary', amount: 2, unit: 'tbsp', calories: 2, optional: false },
      { name: 'fresh thyme', amount: 1, unit: 'tbsp', calories: 1, optional: false },
      SEED_INGREDIENTS.salt(1),
      SEED_INGREDIENTS.pepper(0.5),
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Pat chicken breasts dry and season generously with salt and pepper.',
      'Heat olive oil in an oven-safe skillet over medium-high heat.',
      'Sear chicken for 3-4 minutes per side until golden brown.',
      'Add minced garlic, rosemary, thyme, and lemon slices to the pan.',
      'Transfer skillet to oven and bake for 15-20 minutes until chicken reaches 165°F internally.',
      'Rest for 5 minutes before serving with pan juices drizzled on top.',
    ],
    nutrition: {
      totalCalories: 920,
      caloriesPerServing: 230,
      protein: 42,
      carbs: 3,
      fat: 8,
      fiber: 1,
    },
    tags: ['healthy', 'high-protein', 'quick', 'gluten-free'],
    likes: 156,
  },
  {
    title: 'Creamy Garlic Parmesan Pasta',
    description: 'Rich and creamy pasta with a velvety garlic parmesan sauce. Ready in under 30 minutes for the ultimate comfort food.',
    imageURL: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    authorId: 'chef_admin',
    authorName: 'Chef Antonio',
    isOfficial: true,
    category: 'dinner',
    cuisine: 'italian',
    difficulty: 'easy',
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    ingredients: [
      SEED_INGREDIENTS.pasta(16),
      SEED_INGREDIENTS.butter(4),
      SEED_INGREDIENTS.garlic(6),
      { name: 'heavy cream', amount: 1.5, unit: 'cup', calories: 819, optional: false },
      SEED_INGREDIENTS.parmesan(4),
      SEED_INGREDIENTS.salt(1),
      SEED_INGREDIENTS.pepper(0.5),
      { name: 'fresh parsley', amount: 2, unit: 'tbsp', calories: 3, optional: true },
    ],
    instructions: [
      'Cook pasta according to package directions. Reserve 1 cup pasta water before draining.',
      'While pasta cooks, melt butter in a large skillet over medium heat.',
      'Add minced garlic and sauté for 1-2 minutes until fragrant.',
      'Pour in heavy cream and bring to a gentle simmer.',
      'Add grated parmesan cheese and stir until melted and smooth.',
      'Add drained pasta to the sauce, tossing to coat.',
      'Add pasta water as needed to reach desired consistency.',
      'Season with salt and pepper, garnish with parsley.',
    ],
    nutrition: {
      totalCalories: 2400,
      caloriesPerServing: 600,
      protein: 18,
      carbs: 62,
      fat: 32,
      fiber: 3,
    },
    tags: ['comfort-food', 'vegetarian', 'pasta', 'quick'],
    likes: 243,
  },
  {
    title: 'Teriyaki Chicken Stir-Fry',
    description: 'A colorful and healthy stir-fry with tender chicken and crisp vegetables in a homemade teriyaki sauce.',
    imageURL: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
    authorId: 'chef_admin',
    authorName: 'Chef Kenji',
    isOfficial: true,
    category: 'dinner',
    cuisine: 'japanese',
    difficulty: 'medium',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    ingredients: [
      SEED_INGREDIENTS.chickenBreast(20),
      SEED_INGREDIENTS.soySauce(4),
      SEED_INGREDIENTS.honey(2),
      SEED_INGREDIENTS.ginger(1),
      SEED_INGREDIENTS.garlic(3),
      SEED_INGREDIENTS.bellPepper(2),
      SEED_INGREDIENTS.broccoli(2),
      { name: 'sesame oil', amount: 1, unit: 'tbsp', calories: 120, optional: false },
      { name: 'cornstarch', amount: 1, unit: 'tbsp', calories: 30, optional: false },
      SEED_INGREDIENTS.rice(2),
    ],
    instructions: [
      'Cut chicken into bite-sized pieces and season with salt.',
      'Mix soy sauce, honey, ginger, garlic, and cornstarch for the teriyaki sauce.',
      'Heat sesame oil in a wok or large skillet over high heat.',
      'Cook chicken pieces until golden brown, about 5-6 minutes. Remove and set aside.',
      'Add bell peppers and broccoli, stir-fry for 3-4 minutes until crisp-tender.',
      'Return chicken to the wok and pour teriyaki sauce over everything.',
      'Cook for 2-3 minutes until sauce thickens and coats the ingredients.',
      'Serve hot over steamed rice.',
    ],
    nutrition: {
      totalCalories: 1800,
      caloriesPerServing: 450,
      protein: 38,
      carbs: 48,
      fat: 12,
      fiber: 4,
    },
    tags: ['asian', 'stir-fry', 'healthy', 'meal-prep'],
    likes: 189,
  },
  {
    title: 'Fluffy Buttermilk Pancakes',
    description: 'Light, fluffy, and absolutely delicious pancakes perfect for a lazy weekend breakfast.',
    imageURL: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
    authorId: 'chef_admin',
    authorName: 'Chef Sarah',
    isOfficial: true,
    category: 'breakfast',
    cuisine: 'american',
    difficulty: 'easy',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    ingredients: [
      SEED_INGREDIENTS.flour(1.5),
      SEED_INGREDIENTS.sugar(0.25),
      { name: 'baking powder', amount: 2, unit: 'tsp', calories: 4, optional: false },
      { name: 'baking soda', amount: 0.5, unit: 'tsp', calories: 0, optional: false },
      SEED_INGREDIENTS.salt(0.5),
      { name: 'buttermilk', amount: 1.5, unit: 'cup', calories: 148, optional: false },
      SEED_INGREDIENTS.eggs(2),
      SEED_INGREDIENTS.butter(3),
      { name: 'vanilla extract', amount: 1, unit: 'tsp', calories: 12, optional: false },
    ],
    instructions: [
      'Whisk together flour, sugar, baking powder, baking soda, and salt in a large bowl.',
      'In another bowl, combine buttermilk, eggs, melted butter, and vanilla.',
      'Pour wet ingredients into dry ingredients and stir until just combined (lumps are okay!).',
      'Heat a griddle or non-stick pan over medium heat. Lightly grease with butter.',
      'Pour 1/4 cup batter for each pancake.',
      'Cook until bubbles form on surface and edges look set, about 2-3 minutes.',
      'Flip and cook another 1-2 minutes until golden brown.',
      'Serve warm with maple syrup and butter.',
    ],
    nutrition: {
      totalCalories: 1600,
      caloriesPerServing: 400,
      protein: 12,
      carbs: 56,
      fat: 14,
      fiber: 2,
    },
    tags: ['breakfast', 'classic', 'comfort-food', 'kid-friendly'],
    likes: 312,
  },
  {
    title: 'Mediterranean Quinoa Bowl',
    description: 'A nutritious and colorful bowl packed with Mediterranean flavors. Great for meal prep!',
    imageURL: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    authorId: 'chef_admin',
    authorName: 'Chef Elena',
    isOfficial: true,
    category: 'lunch',
    cuisine: 'mediterranean',
    difficulty: 'easy',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    ingredients: [
      { name: 'quinoa', amount: 1, unit: 'cup', calories: 222, optional: false },
      { name: 'cucumber', amount: 1, unit: 'medium', calories: 30, optional: false },
      { name: 'cherry tomatoes', amount: 1, unit: 'cup', calories: 27, optional: false },
      { name: 'kalamata olives', amount: 0.5, unit: 'cup', calories: 77, optional: false },
      { name: 'feta cheese', amount: 4, unit: 'oz', calories: 300, optional: false },
      { name: 'red onion', amount: 0.25, unit: 'medium', calories: 11, optional: false },
      { name: 'chickpeas', amount: 1, unit: 'can', calories: 269, optional: false },
      SEED_INGREDIENTS.oliveOil(3),
      SEED_INGREDIENTS.lemon(1),
      { name: 'fresh dill', amount: 2, unit: 'tbsp', calories: 1, optional: true },
    ],
    instructions: [
      'Rinse quinoa and cook according to package directions. Let cool.',
      'While quinoa cooks, dice cucumber, halve tomatoes, and slice red onion.',
      'Drain and rinse chickpeas.',
      'Whisk together olive oil, lemon juice, salt, and pepper for dressing.',
      'In a large bowl, combine cooled quinoa, vegetables, chickpeas, and olives.',
      'Pour dressing over salad and toss to combine.',
      'Crumble feta cheese on top and garnish with fresh dill.',
      'Serve immediately or refrigerate for meal prep.',
    ],
    nutrition: {
      totalCalories: 1200,
      caloriesPerServing: 300,
      protein: 14,
      carbs: 32,
      fat: 14,
      fiber: 6,
    },
    tags: ['healthy', 'vegetarian', 'meal-prep', 'gluten-free'],
    likes: 278,
  },
];

// Function to seed recipes to Firebase (call this from admin panel or script)
export const seedRecipesToFirebase = async (
  createRecipeFn: (recipe: Omit<Recipe, 'id' | 'createdAt'>) => Promise<string>
): Promise<void> => {
  for (const recipe of SEED_RECIPES) {
    try {
      await createRecipeFn(recipe);
      console.log(`Seeded: ${recipe.title}`);
    } catch (error) {
      console.error(`Failed to seed: ${recipe.title}`, error);
    }
  }
};
